spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  jwt:
    secret: "" # use the SecretKeyGenerator to generate a secret key and paste it here
    expiration: 100000 # 7 days in milliseconds
